quickbeam data crawl \
  --routes ~/fangorn/embeddings/examples/cc/routes_grants.json \
  --extractors ~/fangorn/embeddings/examples/cc/extractors/ \
  --url https://simpler.grants.gov/search \
  --url https://sloan.org/grants-database \
  --url https://www.mcgovern.org/grants/ \
  --url https://www.grantchain.eu/grants/ \
  --url https://alpha.grand-delivery.eu/api/v1/calls/ \
  --url https://octant.build/api/v1/epochs/ \
  --url https://raw.githubusercontent.com/ospo/ \
  --url https://raw.githubusercontent.com/numfocus/ \
  --url https://raw.githubusercontent.com/chanzuckerberg/ \
  --url https://forum.dfinity.org/c/developer-grants/ \
  --url https://research.lido.fi/c/grants/ \
  --url https://gov.optimism.io/c/grants/ \
  --url https://governance.aave.com/c/grants-program/ \
  --match-type prefix \
  --limit 5000 \
  --n-proc 8 \
  --extract-timeout 7200 \
  --out ~/fangorn/embeddings/examples/cc/grants_universe.json \
  --aggregator free \
  --cmon-bin ~/fangorn/embeddings/cmon_venv/bin/cmon