// Exercises the REAL graph logic (src/lib/graph.ts — the same code the worker runs)
// against a live `cdn serve`, without a browser.
//
// It asserts the things the demo actually claims, so a regression fails here rather
// than in front of an audience:
//   1. the snapshot loads and both publishers are present
//   2. semantic search returns sane, on-topic results
//   3. searching the artist's name returns the platform's stub AND the artist's own
//      record — two different wallets
//   4. relation rails resolve, and the ones marked `crosses` really do join records
//      published by different wallets
//   5. every edge endpoint resolves (a dead end in the CDN is a dead end in the UI)
//
// Usage: quickbeam cdn serve --cdn-dir ./audius-build/cdn --cors --port 8090
//        npm run check:graph
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { Graph } from '../src/lib/graph.ts';

const CDN = process.env.VITE_CDN_URL ?? 'http://localhost:8090';
const DOMAIN = process.env.VITE_DOMAIN ?? 'audius';
const PLATFORM = (process.env.VITE_PLATFORM_OWNER ?? '0x1111111111111111111111111111111111111111');
// The linkset as generated by `audius-link` — the ground truth for how many edges
// genuinely cross between the two publishers.
const LINKSET_PATH = process.env.LINKSET_PATH
  ?? fileURLToPath(new URL('../../audius-build/linkset.json', import.meta.url));

let failures = 0;
async function check(name: string, fn: () => void | Promise<void>) {
  try { await fn(); console.log(`✓ ${name}`); }
  catch (e) { failures++; console.log(`✗ ${name}\n    ${(e as Error).message}`); }
}

const g = new Graph();
console.log(`· loading ${DOMAIN} from ${CDN}`);
const stats = await g.load(CDN, DOMAIN, PLATFORM, (phase, pct) => {
  if (phase === 'ready') console.log(`  loaded ${g.size} records (${pct}%)`);
});

const [platform, artist] = stats.publishers;

await check('both publishers are present', () => {
  assert.equal(stats.publishers.length, 2, `expected 2 publishers, got ${stats.publishers.length}`);
  assert.equal(platform.owner.toLowerCase(), PLATFORM.toLowerCase(), 'platform must sort first');
  assert.ok(artist.total > 0, 'artist publisher has no records');
});

await check('the artist publisher names itself from its own record', () => {
  assert.ok(artist.label, 'no label derived — the ledger would read "the artist"');
  assert.ok(artist.labelId, 'no labelId — the ledger heading would not be clickable');
});

await check('the linkset joins the two roots', () => {
  assert.ok(stats.linksetTotal > 0, 'no cross-publisher edges at all');
  const rels = stats.linkset.map((l) => l.rel);
  assert.ok(rels.includes('sameAs'), `no sameAs edge; got ${rels.join(', ')}`);
});

await check('the crossing count matches the real linkset, not the merged edge file', () => {
  // The hero prints this number, so it has to be the linkset — not every edge whose
  // endpoints happen to carry different owners. Converged vocabulary vertices collapse
  // to a single record with a single owner, which once inflated this from 113 to 12,657.
  let linkset: { count: number };
  try { linkset = JSON.parse(readFileSync(LINKSET_PATH, 'utf8')); }
  catch { console.log(`    (no linkset at ${LINKSET_PATH}; skipping exact match)`); return; }
  assert.equal(stats.linksetTotal, linkset.count,
    `hero would claim ${stats.linksetTotal} crossing edges; the linkset has ${linkset.count}`);
});

await check('every edge endpoint resolves to a served record', async () => {
  // A dangling endpoint is a rail that renders empty in the UI, so this is the same
  // 0-unresolved guarantee the pipeline asserts, re-checked on what's actually served.
  const served: { edges: Array<{ from: string; to: string }> } =
    await (await fetch(`${CDN}/domains/${DOMAIN}/edges`)).json();
  const dangling = served.edges.filter((e) => !g.entity(e.from) || !g.entity(e.to));
  assert.equal(dangling.length, 0,
    `${dangling.length} of ${served.edges.length} edges point outside the snapshot`);
});

console.log('· embedding queries (first call downloads the model)');
const hits = await g.search('dark acid groove house with a moody bassline', 20);

await check('semantic search returns on-topic tracks', () => {
  assert.ok(hits.length > 0, 'no results');
  assert.ok(hits.slice(0, 5).some((h) => h.entityType === 'Track'), 'no tracks in the top 5');
  assert.ok((hits[0].score ?? 0) > 0.5, `top score ${hits[0].score} looks like noise`);
});

const byName = await g.search(artist.label as string, 30);

await check('the artist search returns BOTH publishers\' records', () => {
  const owners = new Set(byName.slice(0, 12).map((h) => (h.owner ?? '').toLowerCase()));
  assert.ok(owners.size > 1,
    `top results all came from one wallet (${[...owners]}) — the split is invisible`);
});

await check('the platform stub and the artist\'s own record both exist', () => {
  const artists = byName.filter((h) => h.entityType === 'Artist');
  const stub = artists.find((a) => a.fields.isReference);
  const real = artists.find((a) => !a.fields.isReference);
  assert.ok(stub, 'no platform reference record');
  assert.ok(real, "no artist-published record");
  assert.notEqual(stub!.owner, real!.owner, 'stub and real record share a wallet');
});

const realArtist = byName.find((h) => h.entityType === 'Artist' && !h.fields.isReference)!;
const rels = g.relations(realArtist.id);

await check('the artist has relation rails, cross-publisher ones first', () => {
  assert.ok(rels.length > 0, 'no relations on the artist node');
  if (rels.some((r) => r.crosses)) {
    assert.ok(rels[0].crosses, 'a crossing rail exists but is not surfaced first');
  }
});

await check('rails marked `crosses` really do join different wallets', () => {
  let checked = 0;
  for (const r of rels.filter((x) => x.crosses)) {
    const { records } = g.neighbours(realArtist.id, r.rel, r.dir, 25);
    const mine = g.ownerOf(realArtist.id);
    assert.ok(records.some((n) => n.owner !== mine),
      `rail ${r.dir}:${r.rel} claims to cross but every neighbour shares the wallet`);
    checked++;
  }
  assert.ok(checked > 0, 'no crossing rails on the artist to verify');
});

await check('a cross-publisher rail resolves to real, nameable records', () => {
  const crossing = rels.find((r) => r.crosses)!;
  const { records, total } = g.neighbours(realArtist.id, crossing.rel, crossing.dir, 5);
  assert.ok(total > 0 && records.length > 0, 'crossing rail resolved to nothing');
  assert.ok(records.every((r) => r.fields.title), 'a neighbour has no title to render');
  console.log(`    e.g. ${crossing.dir}:${crossing.rel} → ` +
    records.slice(0, 3).map((r) => `${r.fields.title}`).join(' · '));
});

await check('the convergence count is real, not just "all vocabulary nodes"', () => {
  const vocabTotal = ['Genre', 'Mood', 'Tag']
    .reduce((n, t) => n + (platform.counts[t] ?? 0) + (artist.counts[t] ?? 0), 0);
  assert.ok(stats.converged > 0, 'no vertices reached by both publishers');
  assert.ok(stats.converged < vocabTotal,
    `converged (${stats.converged}) should be a subset of ${vocabTotal} vocabulary nodes`);
});

console.log(
  `\n${stats.records.toLocaleString()} records · ${stats.edges.toLocaleString()} edges · ` +
  `${stats.linksetTotal} crossing · ${stats.converged} converged vertices`);
if (failures) { console.error(`\n${failures} check(s) failed`); process.exit(1); }
console.log('All graph checks passed.');
